/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */

#include <panic.h>
#include <string.h>
#include "sink_gatt_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Characteristic Declaration 2a05 */
    0x3005, 0x2003, 0x0005, 0x2a00,
    /* 0003:  */
    0xd000,
    /* 0004: Client Characteristic Configuration */
    0x6400,
    /* 0005: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0006: Characteristic Declaration 2a00 */
    0x3005, 0x0207, 0x0000, 0x2a00,
    /* 0007:  */
    0xd400,
    /* 0008: Characteristic Declaration 2a01 */
    0x3005, 0x0209, 0x0001, 0x2a00,
    /* 0009:  */
    0xd400,
    /* 000a: Primary Service 1804 */
    0x0002, 0x0418,
    /* 000b: Characteristic Declaration 2a07 */
    0x3045, 0x020c, 0x0007, 0x2a00,
    /* 000c: . */
    0xd401, 0x0000,
    /* 000d: Primary Service 1802 */
    0x0002, 0x0218,
    /* 000e: Characteristic Declaration 2a06 */
    0x3005, 0x040f, 0x0006, 0x2a00,
    /* 000f: . */
    0xd501, 0x0000,
    /* 0010: Primary Service 1803 */
    0x0002, 0x0318,
    /* 0011: Characteristic Declaration 2a06 */
    0x3045, 0x0a12, 0x0006, 0x2a00,
    /* 0012: . */
    0xd501, 0x0000,
    /* 0013: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0014: Characteristic Declaration 2a19 */
    0x3005, 0x1215, 0x0019, 0x2a00,
    /* 0015: . */
    0xd401, 0x0000,
    /* 0016: Characteristic Presentation Format, rfu, 0 */
    0x8c07, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 0017: Client Characteristic Configuration */
    0x6c00,
    /* 0018: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0019: Characteristic Declaration 2a19 */
    0x3005, 0x121a, 0x0019, 0x2a00,
    /* 001a: . */
    0xd401, 0x0000,
    /* 001b: Characteristic Presentation Format, rfu, 0 */
    0x8c07, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 001c: Client Characteristic Configuration */
    0x6c00,
    /* 001d: Primary Service 180f */
    0x0002, 0x0f18,
    /* 001e: Characteristic Declaration 2a19 */
    0x3005, 0x121f, 0x0019, 0x2a00,
    /* 001f: . */
    0xd401, 0x0000,
    /* 0020: Characteristic Presentation Format, rfu, 0 */
    0x8c07, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 0021: Client Characteristic Configuration */
    0x6c00,
};

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

uint16 GattGetDatabaseSize(void)
{
    return sizeof(gattDatabase);
}

/* End-of-File */
